approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: true

enableImmutableInstalls: false

enableStrictSsl: true

enableTelemetry: false

nodeLinker: node-modules

npmMinimalAgeGate: 1d
