approvedGitRepositories:
  - "**"
enableScripts: true
nodeLinker: node-modules
npmMinimalAgeGate: 1d
enableGlobalCache: true
compressionLevel: mixed
enableTelemetry: false
enableImmutableInstalls: true
enableStrictSsl: true